insert into miestas (pavadinimas, id_Miestas) values ('Sainte-Sophie', 1);
insert into miestas (pavadinimas, id_Miestas) values ('Tacurong', 2);
insert into miestas (pavadinimas, id_Miestas) values ('Santo Amaro', 3);
insert into miestas (pavadinimas, id_Miestas) values ('Yilongyong', 4);
insert into miestas (pavadinimas, id_Miestas) values ('Strängnäs', 5);
insert into miestas (pavadinimas, id_Miestas) values ('Heqian', 6);
insert into miestas (pavadinimas, id_Miestas) values ('Rū-ye Sang', 7);
insert into miestas (pavadinimas, id_Miestas) values ('Yuntan', 8);
insert into miestas (pavadinimas, id_Miestas) values ('Cam Ranh', 9);
insert into miestas (pavadinimas, id_Miestas) values ('Tiadiaye', 10);
insert into miestas (pavadinimas, id_Miestas) values ('Barentu', 11);
insert into miestas (pavadinimas, id_Miestas) values ('Okhtyrka', 12);
insert into miestas (pavadinimas, id_Miestas) values ('Lamadong', 13);
insert into miestas (pavadinimas, id_Miestas) values ('Chaumont', 14);
insert into miestas (pavadinimas, id_Miestas) values ('Loncoche', 15);
insert into miestas (pavadinimas, id_Miestas) values ('Staryy Dobrotvir', 16);
insert into miestas (pavadinimas, id_Miestas) values ('Domont', 17);
insert into miestas (pavadinimas, id_Miestas) values ('Ibshawāy', 18);
insert into miestas (pavadinimas, id_Miestas) values ('El Cerrito', 19);
insert into miestas (pavadinimas, id_Miestas) values ('Airuk', 20);
insert into miestas (pavadinimas, id_Miestas) values ('Severnyy', 21);
insert into miestas (pavadinimas, id_Miestas) values ('Kallithéa', 22);
insert into miestas (pavadinimas, id_Miestas) values ('Meishan', 23);
insert into miestas (pavadinimas, id_Miestas) values ('Czarnocin', 24);
insert into miestas (pavadinimas, id_Miestas) values ('As Salţ', 25);
insert into miestas (pavadinimas, id_Miestas) values ('Caaguazú', 26);
insert into miestas (pavadinimas, id_Miestas) values ('Nowe Grocholice', 27);
insert into miestas (pavadinimas, id_Miestas) values ('Meiyuan Xincun', 28);
insert into miestas (pavadinimas, id_Miestas) values ('La Esperanza', 29);
insert into miestas (pavadinimas, id_Miestas) values ('Tassin-la-Demi-Lune', 30);
insert into miestas (pavadinimas, id_Miestas) values ('Xinshi', 31);
insert into miestas (pavadinimas, id_Miestas) values ('Svetlograd', 32);
insert into miestas (pavadinimas, id_Miestas) values ('Carregal', 33);
insert into miestas (pavadinimas, id_Miestas) values ('Buenavista', 34);
insert into miestas (pavadinimas, id_Miestas) values ('Vostok', 35);
insert into miestas (pavadinimas, id_Miestas) values ('Oliveira de Frades', 36);
insert into miestas (pavadinimas, id_Miestas) values ('Catac', 37);
insert into miestas (pavadinimas, id_Miestas) values ('Kaolack', 38);
insert into miestas (pavadinimas, id_Miestas) values ('San José de Miranda', 39);
insert into miestas (pavadinimas, id_Miestas) values ('Boliden', 40);
insert into miestas (pavadinimas, id_Miestas) values ('Pasirputih', 41);
insert into miestas (pavadinimas, id_Miestas) values ('Huzhen', 42);
insert into miestas (pavadinimas, id_Miestas) values ('Tilburg', 43);
insert into miestas (pavadinimas, id_Miestas) values ('Iecava', 44);
insert into miestas (pavadinimas, id_Miestas) values ('Sremski Karlovci', 45);
insert into miestas (pavadinimas, id_Miestas) values ('Al Ḩarf', 46);
insert into miestas (pavadinimas, id_Miestas) values ('Anyu', 47);
insert into miestas (pavadinimas, id_Miestas) values ('Yafran', 48);
insert into miestas (pavadinimas, id_Miestas) values ('Baliang', 49);
insert into miestas (pavadinimas, id_Miestas) values ('Calçada', 50);
