insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('SODIUM BORATE, CALENDULA OFFICINALIS FLOWERING TOP, CANDIDA ALBICANS, GOLDENSEAL', 'Obsv-adolesc antisoc beh', 1);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('BENZALKONIUM CHLORIDE', 'Neurogenic bowel', 2);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Neomycin and Polymyxin B Sulfates', 'Nodular lymphoma pelvic', 3);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Trandolapril', 'Fetal abnorm NEC-antepar', 4);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Timolol Maleate', 'Myelodysplastic synd NOS', 5);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('SODIUM FLUORIDE', 'West Nile Fever w/enceph', 6);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('ALCOHOL', 'Macular degeneration NOS', 7);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('nicotine', 'Syphilis of muscle', 8);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl', 'Colles'' fracture-open', 9);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Octinoxate and Titanium dioxide', 'Intestin TB NEC-histo dx', 10);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Venlafaxine', 'Rh incompat reaction NEC', 11);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('DIVALPROEX SODIUM', 'Jt derangement NEC-l/leg', 12);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Titanium dioxide', 'Fecal smearing', 13);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('prochlorperazine', 'Machine dependence NEC', 14);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Cephalexin', 'Joint dis NEC-forearm', 15);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Acetaminophen, Diphenhydramine HCl, Phenylepherine HCl', 'Cerb deg chld in oth dis', 16);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('naproxen', 'Transv vaginal septum', 17);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Water', 'Fx c3 vertebra-closed', 18);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Black Olive', '1st deg burn face NEC', 19);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('MIDAZOLAM HYDROCHLORIDE', 'Malposition NOS-deliver', 20);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Sardine', 'Malign neopl vulva NOS', 21);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('morphine sulfate', 'Chr interstit cystitis', 22);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Propranolol Hydrochloride', 'Deformity of orbit NOS', 23);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('verapamil hydrochloride', 'Mat comp in utro-del-p/p', 24);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('levothyroxine sodium', 'Cutaneous-vesicos status', 25);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Metformin Hydrochloride', 'Mv coll w ped-anim rid', 26);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('bacitracin, neomycin, polymyxin B', 'Pois-nerve/plex-blk anes', 27);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Nicotine Polacrilex', 'Bone injury NEC at birth', 28);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Naproxen Sodium', 'Plastic surgery NEC', 29);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('diphenhydramine hydrochloride', 'No proc/patient decision', 30);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Isosorbide Dinitrate', 'Intrathoracic inj NEC-cl', 31);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Alcohol', 'Mal neo soft tissue arm', 32);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Avobenzone, Octisalate, Octocrylene, and Oxybenzone', 'Loss control mv acc-psgr', 33);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl', 'Adrenal disorder NOS', 34);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('ALCOHOL', 'Observ-suspect cond NOS', 35);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Sulfur', 'Fx c3 vertebra-closed', 36);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Benzonatate', 'Gonorrhea-delivered', 37);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('OCTINOXATE, TITANIUM DIOXIDE', 'Poisoning-bcg vaccine', 38);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Calendula officinalis, Nux vomica, Silicea,', 'Chr duoden ulcer w perf', 39);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('NAFCILLIN', 'Prsnl hst colonic polyps', 40);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Dextromethorphan Hydrobromide, GUAIFENESIN,', 'Urethral diverticulum', 41);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Hydrocodone Bitartrate and Acetaminophen', 'Glauc w inc episcl press', 42);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('purified water', 'Adv eff antithyroid agnt', 43);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Triclosan', 'Fracture of sternum-open', 44);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Hydrocortisone', 'Termination of pregnancy', 45);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Athomer', 'Postinfectious myelitis', 46);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Cladosporium Cladosporioides Hormodendrum Clad', 'Heavy-for-date infan NEC', 47);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Diltiazem Hydrochloride', 'Adv eff ovarian hormones', 48);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Piroxicam', 'Actv Meniere,cochlvestib', 49);
insert into Paslauga (pavadinimas, aprasymas, id_Paslauga) values ('Promethazine Hydrochloride', 'Cns TB NOS-unspec', 50);
